### ISSUE TITLE
prism.css file line 44 have a error

### ISSUE THREAD

**Issue by liu1084** [digitalocean/nginxconfig.io#472]
prism.css file line 44:

```css
pre[class*="language-"] > code[data-prefix]:before {
  color: $676767;
  content: attr(data-prefix);
  padding-right: 8px;
}
```

shoud be:
```css
pre[class*="language-"] > code[data-prefix]:before {
  color: #676767;
  content: attr(data-prefix);
  padding-right: 8px;
}
```
